kernel:
    resource: ../src/Kernel.php
    type: annotation

app_main_page:
    path: /
    methods: [GET,POST]
    controller: app.controller.main_page_controller
app_data:
    path: /data
    controller: app.controller.show_data_controller
app_register:
    path: /register
    controller: app.controller.register
app_login:
    path: /login
    controller: app.controller.login
app_logout:
    path: /logout
    methods: GET

